<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>NETSDK1233</NoWarn>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Rotherprivat.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="MSTest" Version="4.2.1" />
    <PackageReference Include="Microsoft.Bcl.Cryptography" Version="10.0.7" Condition="'$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="System.Formats.Asn1" Version="10.0.7" Condition="'$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KemBasedNet\KemBasedNet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Cryptography\testvectors.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
