using System.Security.Cryptography;

namespace Rotherprivat.KemBasedNet.Cryptography.Internal
{
    // Generated By AI-ChatGPT
    internal static class Rfc3394
    {
        // Default IV defined by RFC 3394
        private static readonly byte[] DefaultIV =
        {
            0xA6, 0xA6, 0xA6, 0xA6,
            0xA6, 0xA6, 0xA6, 0xA6
        };

        public static byte[] Wrap(ReadOnlySpan<byte> kek, ReadOnlySpan<byte> plaintext)
        {
            if (plaintext.Length < 16 ||
                plaintext.Length % 8 != 0)
            {
                throw new ArgumentException(
                    "Plaintext must be at least 16 bytes and multiple of 8.");
            }

            int n = plaintext.Length / 8;

            byte[] A = [.. DefaultIV];

            byte[][] R = new byte[n][];

            for (int i = 0; i < n; i++)
            {
                R[i] = new byte[8];
                for (int j = 0; j < 8; j++)
                    R[i][j] = plaintext[i * 8 + j];
            }

            using Aes aes = Aes.Create();

            aes.Key = kek.ToArray();
            aes.Mode = CipherMode.ECB;
            aes.Padding = PaddingMode.None;

            using ICryptoTransform encryptor =
                aes.CreateEncryptor();

            byte[] block = new byte[16];

            for (int j = 0; j < 6; j++)
            {
                for (int i = 0; i < n; i++)
                {
                    // B = AES(K, A | R[i])

                    Buffer.BlockCopy(A, 0, block, 0, 8);
                    Buffer.BlockCopy(R[i], 0, block, 8, 8);

                    encryptor.TransformBlock(
                        block,
                        0,
                        16,
                        block,
                        0);

                    ulong t = (ulong)((n * j) + (i + 1));

                    // A = MSB(64, B) ^ t

                    A = new byte[8];

                    Buffer.BlockCopy(block, 0, A, 0, 8);

                    XorT(A, t);

                    // R[i] = LSB(64, B)

                    Buffer.BlockCopy(block, 8, R[i], 0, 8);
                }
            }

            byte[] result = new byte[(n + 1) * 8];

            Buffer.BlockCopy(A, 0, result, 0, 8);

            for (int i = 0; i < n; i++)
            {
                Buffer.BlockCopy(
                    R[i],
                    0,
                    result,
                    (i + 1) * 8,
                    8);
            }

            return result;
        }

        public static byte[] Unwrap(byte[] kek, byte[] ciphertext)
        {
            if (ciphertext == null)
                throw new ArgumentNullException(nameof(ciphertext));

            if (ciphertext.Length < 24 ||
                ciphertext.Length % 8 != 0)
            {
                throw new ArgumentException(
                    "Ciphertext must be at least 24 bytes and multiple of 8.");
            }

            int n = (ciphertext.Length / 8) - 1;

            byte[] A = new byte[8];

            Buffer.BlockCopy(ciphertext, 0, A, 0, 8);

            byte[][] R = new byte[n][];

            for (int i = 0; i < n; i++)
            {
                R[i] = new byte[8];

                Buffer.BlockCopy(
                    ciphertext,
                    (i + 1) * 8,
                    R[i],
                    0,
                    8);
            }

            using Aes aes = Aes.Create();

            aes.Key = kek;
            aes.Mode = CipherMode.ECB;
            aes.Padding = PaddingMode.None;

            using ICryptoTransform decryptor =
                aes.CreateDecryptor();

            byte[] block = new byte[16];

            for (int j = 5; j >= 0; j--)
            {
                for (int i = n - 1; i >= 0; i--)
                {
                    ulong t = (ulong)((n * j) + (i + 1));

                    byte[] aXorT = A.ToArray();

                    XorT(aXorT, t);

                    // B = AES-1(K, (A ^ t) | R[i])

                    Buffer.BlockCopy(aXorT, 0, block, 0, 8);
                    Buffer.BlockCopy(R[i], 0, block, 8, 8);

                    decryptor.TransformBlock(
                        block,
                        0,
                        16,
                        block,
                        0);

                    // A = MSB(64, B)

                    Buffer.BlockCopy(block, 0, A, 0, 8);

                    // R[i] = LSB(64, B)

                    Buffer.BlockCopy(block, 8, R[i], 0, 8);
                }
            }

            // Verify integrity IV

            if (!A.SequenceEqual(DefaultIV))
            {
                throw new CryptographicException(
                    "RFC3394 integrity check failed.");
            }

            byte[] result = new byte[n * 8];

            for (int i = 0; i < n; i++)
            {
                Buffer.BlockCopy(
                    R[i],
                    0,
                    result,
                    i * 8,
                    8);
            }

            return result;
        }

        private static void XorT(byte[] block, ulong t)
        {
            for (int k = 0; k < 8; k++)
            {
                block[7 - k] ^= (byte)(t & 0xFF);
                t >>= 8;
            }
        }
    }
}
