name: Build, Test and Deploy CompositeMLKem

on:
  push:
    tags:
      - 'v*'
      - 'V*'

permissions:
  id-token: write

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x
 
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore -p:IncludeSourceRevisionInInformationalVersion=false

      - name: Run tests
        run: dotnet test --configuration Release --no-build

      - name: Build Nuget-Package
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish the package to nuget.org
        shell: pwsh
        run: |
          Get-ChildItem ./nupkg/*.nupkg | ForEach-Object {
            dotnet nuget push $_.FullName --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
          }
