name: Build KemBasedNet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x
          source-url: https://nuget.pkg.github.com/rotherprivat/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build

      - name: Publish only the library dotNET10.0
        run: dotnet publish "./KemBasedNET/KemBasedNet.csproj" --configuration Release --no-build --framework "net10.0" --output ./publish/net10.0

      - name: Publish only the library dotNET8.0
        run: dotnet publish "./KemBasedNET/KemBasedNet.csproj" --configuration Release --no-build --framework "net8.0" --output ./publish/net8.0

      - name: Build Nuget-Package
        run: dotnet pack --configuration Release --output ./nupkg

      - name: Publish the package to GPR
        shell: pwsh
        run: |
          Get-ChildItem ./nupkg/*.nupkg | ForEach-Object {
            dotnet nuget push $_.FullName --api-key "${{ secrets.NUGET_API_KEY }}"
          }
        
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: KemBasedNET-binaries
          path: ./publish
